language: python
sudo: required
python:
- '2.7'
install: pip install -r requirements.txt
script: echo \"TODO\"
deploy:
  provider: lambda
  function_name: lambda-test
  role: arn:aws:iam::109549055893:role/iam_role_for_lambda
  handler_name: lambda_function.lambda_handler
  access_key_id:
    secure: "fAvv0HIy9Yy1A04OF5t6/TdyCG3oAz+cfQ2RIO+WkKnTX46b9fb3S6uEG33vL0OYEZcC6At5KlNbauCLjPvZyQJWZ+Ct3u484/R0FaYe1UqOAoT53+ty3tVbPjtGzgbDjKv9pJjYufLBuHIfZqPXOGNoIKGwPvpMWjDIPfNfp/8X7CJYBgyICBEh26cdIZCFKTPX1oZgcka0/wEKINCoKLDhotI4h3IuEq0Z9YfjmBIyD/Kq+xqMcT/DwrDkjowvK8D2GyPi0dsExWulB/2V9w6FgXDDd2EXBKW1lfXxpfRik7i7Pd5Lg5IUFSnF7ZLr+9mbXijFu/6sQ19rW7HZ9TqrJ4GUjn9cIbLMpHBZR9IvN2M0r68af7hNsxlx854a7YSR9h94nz/Uv+ogHh3DtJ57YBbr2JmKKt6449HdRtWVt+kNrMBWNzFeW3671TTr1J/DhRYdJ0nw+fgsqVxsMH3vekw8dsvdjisjlqtS1ovSc/jzfW7IsBwcmk76TAKv96z+t3HkP8q6Cw5hmfQAp5aBH/wgXi8BeMCd/wV/YWONV76Hb+aTGVjKJP4OwVp+wNkdGYgN97ypbwZW0mQSMp6NfOViZkEVksZP4VmNbLR74WO61Xgab5LuuxNg3J3G56ZSVrLq1D76TTKiPCwwm6opQx+hSBNQP5pJAw13k3g="
  secret_access_key:
    secure: "tREN7fstlzH8mqj9gysH4v1AKZ2Iizv/65cCagGsh8e3TAm7iN7DEs8+TEUHm2NlVH7rH1wrZBt9jwzXg4XJOZ9pkAM4zIAvO7r0xnYNSKh79YLSV4DyPpfofe3lMgmmXO5qD3QgqcilcBN4CyJbjg7jKQRp7/lIpA+abmLvw6rsMwYKYagSuueZvd18+IgpQL51/kMCN8cjsxfBYVAAcayQgXOMxQbS7oSCNCED0sjI+sfUQ8ISyhw6eFqaXO0l1+/hLxMIaUx15Z4jhJj+xx+hJwDE+gAUUcmDv79tDePfKQ4BlHFHp/yRZ7E6pE0aVkEbhJNPyrCUHvTn7A5DHyo6MkeSNQRNK55dq1YKrliTbTTQJG7FHpCI6k80g7Yu0ZDZbBVw3As+L4h8gIwwrZ2O85mMeguaTTdlFKH0ApbdHq6p+T8FkSpSCi6dASHX9ZfE0pq+1mGYvgDbiq5qzzyk9KiYJCXu4raRCwSnMBMz2lIzKH+4H1tEnujpDBgXeem6WRFmTizbQ+zrV0bkuQXJYYfWHr0gR3eEXUTDy5GltkBLZ+iobUXUhD0tMlT7+SjeGL1sr6q85b4efBYfSEysg9v9vAoGm9poP1NNhMb4rHfm8POJ/w3IRrkBz8FePh1Hn00tO/wh/+g0w20p3R6CCqecuZ4TL9pYj1No1YM="

