language: python
sudo: required
python:
- '2.7'
before_install:
  - chmod +x ./ci-package.sh
install: ./ci-package.sh
script: echo "$DOES_IT_WORK"
deploy:
  provider: lambda
  function_name: "figshare-worker"
  role: arn:aws:iam::458323522494:role/lambda_kinesis_iam_role
  handler_name: lambda_handler
  module_name: figshare-worker
  zip: "figshare-worker.zip"
  runtime: "python2.7"
  access_key_id: "$ACCESS_KEY_ID"
  secret_access_key: "$SECRET_ACCESS_KEY"
  region: us-east-1