language: python
sudo: required
python:
- '2.7'
install: pip install -r requirements.txt
script: echo \"TODO\"
deploy:
  provider: lambda
  function_name: lambda-test
  role: arn:aws:iam::109549055893:role/iam_role_for_lambda
  handler_name: index.handler
  access_key_id: "AWS_ACCESS_KEY"
  secret_access_key: "AWS_SECRET_KEY"
env:
  matrix:
  - secure: HO0RwWmjvzNSgreUdes82lp/jCnJCMceIq7AIjnOKuvbShLJPGwu5yxMk8NvFxQku6J1LTXoZ2VxjfXjBKS2i9orzGp5HImXBoJwy5eEodk0hEmM8fsey0slFOsmPEWwH5wyZ9oVY9KE7wSxAIy+EA+hTXlFmrzvnhungc+RF6MNtA1j2BB8CUbx8CjkDzU3bCwwgI3Sj26dZ1mSV/GG3cFNwZLTl0pWOPF0H4sjzSiJGg2aXFXkZTL1ifiqibr7x2nLzbr3bduc3CKWadOS95wCld9Uk/UDqFWhbJtnG7xCSd1b1fQDloKrvszilh66NR+fgWZx4YDKtjug2CnlkADpSMUuoDAebV0BpBOIv9akOYzdh5ZCr96xQlwN6fV3K69439vDo5AG0UNnQJ5fylzeTaTwg9nomVUYtuhlZHrq3WZNcaz9TwX3bsIawC2uciWuKst33DN46V2lEm0O9PHr5UMBuRBT0rWjat41QQobD7tD4qofzabTFflqe7QsesffiKrI7+dfuGnbhQDeYgXO9rCKm89zLnshsxMrBxYci8QC+v9GrBV35LOZL/nVe7c1njDpuz3WXwRxYK4w3PDEumEe1vMvzxP+WM/K5HgYkNPQnBWpEczSCzOLmLn0efr/D5aA1ryjhtsqFBcUMYbTE4wROt1KE2DFl7xrtL0=
  - secure: lBFoNo9imZcUsLCaQfwYDClOwZwa1SDyQ1jZAErbkTuAyof3zN5P3+J3BDMgbh4Tg9I45nBXjkpMEWWeYS4We9wDqLGQiom0WMHV0avXzlyh/EcyHLUWSoIECVc6klQAel2eFyI0Dj+VpITwul5wALnehdpIKGzHuHlyN2dZ6qh+UB8F7qcxWqkkoGDNCsLinNLQfZsLPB8jrH0/DKipQuuiUeeK/iknt+fqsegLxwejeWKPmZMDf3Oh14ZkmLigwWoUktJYfZPBDSIxPjjmbPsirKOobcZ3Y6nVuzWnkN/JkC/Ym/CkM2A1UUzHA/uEQa65a8hBG8b1p4XDkFtXP8g5HhwgPpIu0AomMfZHVxmwiApcQg4JOICUD7G2iDHHSosWcDQ0AErn8BAhkF9F93US3jEAeT1FPiNsVjnKJwxWtwMkHw5UhX1H+ebJI3cyHoXLoFouuze55JRqAkoilaKbCK9M6qDv7+QCFjZY+5zwFHJ1V+3cIL/8WZsO1yLCi8Lw69dGvXRMay/gnEL2tInhc/sCCIGGW58MeDehJg4l2wodksgbt/FxHXEfoY3uy5/n/h6MfvdlTDrPLDYayg/1RgOfh0E0ZZeG8xOarQFUsxvPNMr6PJyzmIl63a3vFA//npPtD3r0KRxuGWYoflfZLdvxSYdeMKmz1HygYPA=
