language: python
sudo: required
python:
- '2.7'
install: pip install -r requirements.txt
script: echo \"TODO\"
deploy:
  provider: lambda
  function_name: lambda-test
  role: arn:aws:iam::109549055893:role/iam_role_for_lambda
  handler_name: index.handler
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
env:
  matrix:
  - secure: acsHmxl+wtTaMKIlUhxbPkSYZwmvMznTH9RS8V2pDVYLwz/1zwrilljE5vu9ukhGKMk93rTMnSdC8JdvVCJ1QqwdOYgT3p0cUlHMCBiXcCkEM3p8TRz3neGqz1s+TKGjvifMSQrZim57C7o6JlI5/YFEPPfWGvsGWHp7idWntYMrovmn8Gf5fPwyFcQhtgfwsMlUFXFl9VwmSRHLgDIka+VTZNmrMxLOrG1gf4yX8XwrN3+WI61eg2xey3qg8xJGHX5pl0qzoZzp5d6DclUeYkB+V4q4+gnQVJq+fYomQ9s4ef4xn+KBm1iAH6gqJOqOhs79grqwnppH3t5Xty0ShGeNUwhq3A1kMyNlNQ2xkUG3McXt41Q4GJBv7Rx0TJgC7tka3HTdbnLI+m4q9TJICKI4PR2rDUZKxN54/PGtqGSMvQ5f5okbYrYh9b6RVo5OdiyKe+b4Ws4mwSZ5eT/qxlEXUlRilH8vCqh7UD45BDDqpCbNktFM5fKfyvN5VphB13rzyOE4fHTdjWM+Qp5uz0Eg+umRZyxreUC4uZB6LxetpBLn8d/c5tRteaXYzyYu/4CO4T4T39bFMFzxPXHC+Cj5yAhwTeeKe3a56JM21DFxUU4ux9ocZ1spAKM81YLCuyjc3XPnTKcHyq78jWPB8PNZrv1bQYFDYhkYkDuEy58=
  - secure: O+L1mt5LFZULoFVc50u3RP3sNvz6645sALX0Goa6ma2bzlRoZ0bGldeUbi1weS3P4wSEW2KVzvqL/AfQy/P7dXTOutgt4TAFm+YYX73aMxzqAt3e311zurOj4Y83FrvurLUxGYW/3O8+/BydR9fbYVPg8XOr26PbqJBI/NctoIbXTQ0GhFYQClM20af7UksgtiS4y05h7qgNWDKeJAW1CA0hmbAYR1YEUgq+bQfWO7c0eje9z4B1xmaqOcGRQo5U5OY2I8CD+fZ8BU8KnZhDNa9ckTHi39emmiZoV+EnmHzc5DIptDnINCm82D8vtYylDDYLH32nEOK7b0ttXxMm9XrMwI9QaqU4s0/vHDNgW9Xe/CUVEGued2zrb0Hh/+KRAOcXvHkBiDwIhSXz5NsTTB0po+DeIzy8hC2b1KB8tqDorT9HOA9lt1P/oRzo2kM9ya4zMDbgBURaOKRz0F8giRJLS3TIF+JzENH5+/t/Boc/lCzBFHOAYFnup4Zb/3deT7KRqaQM8PGxEtcURtIgCT1g6eB2PV15ponQFWZ/m5gj7r361Enkdc9N4ciJ/UBRm7O139YOeRTiRQQf3gU/C28eUDQjU9Ogt71gI/akujET4cf2mmKZnF0v60KdwpfonGAuR/2QmUD/p4w8R2Dd5dP6zimkg1DxqIFkMv5qfpk=
