language: python
sudo: required
python:
- '2.7'
install: pip install -r requirements.txt
script: echo \"TODO\"
deploy:
  provider: lambda
  function_name: lambda-test
  role: arn:aws:iam::109549055893:role/iam_role_for_lambda
  handler_name: lambda_function.lambda_handler
env:
  secret_access_key:
    secure: GSybQC7D66byOKNC3c9sYaF0QOFQVAZ/MoLSwj6eAGH8SGRY05N5JLvAd4NeknzOQ4ILxA0w7tiaPpCJ2qEZbmESWuq7dLqr6AtZasx6QGbSzTE425RB/Ep1/nrQGjOqmrFaqm1JSl8RXNtqnoB0lto3Gr0A1UEwJ4NSxuW1ro7aIjUATNw6ksBAS2NZYe/vPqug0zoJu1w0V21amTbkNxI+1G99a+oVtF5mZNmCfCzPLBpuSSFYNKMsfcECbi4Wq9dzqXxoDZv3l7lR/XOBJE6R1E4kjgUxLcbeBMRPdGcrI1y7zFL/k+r6GVbEiR+zDhtmvaqbRiL3W6F727MGuEmHpaD/5k5ZbIMSnPTj6Ro/E5sdRfP8XV7RzL4kKR8AsHP6lUu6EwF4lF0vgux3lPIp4UjixjQee1ngeFT2tVPLN/+gdAz/rd0jxapPnCnCAstX8adOZ5bYq14ru46cuS1dBJJfvFmUrv8mxq0KT8okUyixWn1w0ut8YJ4U28GXE64mrH3kq352ysrSJ+hG5jrE3urv2MDps6IWispeq+Gh6pR+XYJaiI0nl6Odcyr0+HVktlycwtal3JTDueLBNokmc7pv67gm3TIMzQ9Aj0ED64alSWUyslEAram+qqGvjVJQhgv5yhJOgTdprWbQwdSW1ebky1dH5vc4O/qFLd8=
  access_key_id:
    secure: FoOLzSVAZh4Y+hF4XTQqB+pRvfmJZ0Jr4I30xFgh3EThXrOYvuuX4NxGtfiZLZdV+aWXsBLWkFdTpNfCMBOn01A45RZLNKC1Dggsq8oktoUKoIIUT99VD6M5Akz1p6pSghMfSxLehGCsNkw26Uc4cBWbAMPjyEFsnKOhePyh/WcIPkO4L8trKe+1AmMzQdGKL+aol0GRP9mjvaILCcceeX91szO5cH/nBglH5UjOcXyk1GNcUy1NPxXOFGF4LngSiXN4U6zbSZrb5N0HhkdBcHHGoobka1JitoaHwnKUEwx57rJ492Ad8GRdcm3Wj5n0GUXLPl0xpC8ebp1lu3dTIzyPnL8aGxpDUZTKi5fLPj/14dq+rAZXBZlel7OhZcedrVVD17gAE5WgB+cW/L3g5O6Q/9tW4ft4sJJBecDXaCFLtBFTvSWLTCpn/5rNYcS8Hzn0zGYzhUr22BqCDQBC+bWnks+0WwLwYyHBCX3fEdtu8ZJRCsW1mJxtDWhdiV9SkFmm0yJcsfrSmVR4jh/Ee3xmwFamQhthh1HI6mOWIyP1hi2MkZZFEyj2Qg/HCH2bC6VLauTJfSjBoHA1eZbAlHWQ73DHdCUSDEPI6utwY1hdJvRRCPUlbyOSP3886gg8T0LuiqJNSOAbxQt+uYy6tKiqNwjwuXdRvdWRxb3Q22Y=
