language: python
sudo: required
python:
- '2.7'
before_install:
  - chmod +x ./travis-install.sh
install: ./travis-install.sh
script: echo "$DOES_IT_WORK"
deploy:
  provider: lambda
  function_name: "figshare-worker"
  role: arn:aws:iam::109549055893:role/iam_role_for_lambda
  handler_name: lambda_handler
  module_name: figshare-worker
  zip: "figshare-worker.zip"
  runtime: "python2.7"
  region: us-east-1