language: python
sudo: required
python:
- '2.7'
install: travis-install.sh
script: echo "$DOES_IT_WORK"
deploy:
  provider: lambda
  function_name: "figshare-worker"
  role: arn:aws:iam::109549055893:role/backwardtestLambdaTravis
  handler_name: lambda_function.lambda_handler
  zip: "figshare-worker.zip"
  runtime: "python2.7"
  access_key_id: "$ACCESS_KEY_ID"
  secret_access_key: "$SECRET_ACCESS_KEY"
  region: us-east-1